import { ReactElement } from "react";

import Css from "../ui/icons/css.svg?react";
import Docker from "../ui/icons/docker.svg?react";
import Eslint from "../ui/icons/eslint.svg?react";
import Firebase from "../ui/icons/firebase.svg?react";
import Fsd from "../ui/icons/fsd.svg?react";
import Git from "../ui/icons/git.svg?react";
import Gitlab from "../ui/icons/gitlab.svg?react";
import Html from "../ui/icons/html.svg?react";
import Js from "../ui/icons/js.svg?react";
import Mui from "../ui/icons/mui.svg?react";
import Nextjs from "../ui/icons/nextJS.svg?react";
import Nginx from "../ui/icons/nginx.svg?react";
import Nodejs from "../ui/icons/nodejs.svg?react";
import React from "../ui/icons/react.svg?react";
import Reactquery from "../ui/icons/reactQuery.svg?react";
import Redux from "../ui/icons/redux.svg?react";
import Sass from "../ui/icons/sass.svg?react";
import Storybook from "../ui/icons/storybook.svg?react";
import Tailwind from "../ui/icons/tailwind.svg?react";
import Ts from "../ui/icons/ts.svg?react";
import Vite from "../ui/icons/vite.svg?react";

// Autogenerated by script - do not edit manually

export type IconType =
    | "css"
    | "docker"
    | "eslint"
    | "firebase"
    | "fsd"
    | "git"
    | "gitlab"
    | "html"
    | "js"
    | "mui"
    | "nextjs"
    | "nginx"
    | "nodejs"
    | "react"
    | "reactquery"
    | "redux"
    | "sass"
    | "storybook"
    | "tailwind"
    | "ts"
    | "vite"

export type IconProps = React.SVGProps<SVGSVGElement>;

export const IconMap: Record<IconType, (props: IconProps) => ReactElement> = {
  ["css"]: ({ ...props }) => <Css {...props} />,
  ["docker"]: ({ ...props }) => <Docker {...props} />,
  ["eslint"]: ({ ...props }) => <Eslint {...props} />,
  ["firebase"]: ({ ...props }) => <Firebase {...props} />,
  ["fsd"]: ({ ...props }) => <Fsd {...props} />,
  ["git"]: ({ ...props }) => <Git {...props} />,
  ["gitlab"]: ({ ...props }) => <Gitlab {...props} />,
  ["html"]: ({ ...props }) => <Html {...props} />,
  ["js"]: ({ ...props }) => <Js {...props} />,
  ["mui"]: ({ ...props }) => <Mui {...props} />,
  ["nextjs"]: ({ ...props }) => <Nextjs {...props} />,
  ["nginx"]: ({ ...props }) => <Nginx {...props} />,
  ["nodejs"]: ({ ...props }) => <Nodejs {...props} />,
  ["react"]: ({ ...props }) => <React {...props} />,
  ["reactquery"]: ({ ...props }) => <Reactquery {...props} />,
  ["redux"]: ({ ...props }) => <Redux {...props} />,
  ["sass"]: ({ ...props }) => <Sass {...props} />,
  ["storybook"]: ({ ...props }) => <Storybook {...props} />,
  ["tailwind"]: ({ ...props }) => <Tailwind {...props} />,
  ["ts"]: ({ ...props }) => <Ts {...props} />,
  ["vite"]: ({ ...props }) => <Vite {...props} />,
};
